# Generated by Django 4.1.7 on 2023-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_identifier",
                    models.CharField(blank=True, max_length=200),
                ),
                ("price", models.CharField(blank=True, max_length=50)),
                ("date_of_transfer", models.DateTimeField()),
                ("postcode", models.CharField(blank=True, max_length=10)),
                ("property_type", models.CharField(blank=True, max_length=20)),
                ("old_or_new", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=50)),
                (
                    "primary_addressable_object_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "secondary_addressable_object_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("property_street", models.CharField(blank=True, max_length=200)),
                ("property_locality", models.CharField(blank=True, max_length=200)),
                ("property_city", models.CharField(blank=True, max_length=200)),
                ("property_district", models.CharField(blank=True, max_length=200)),
                ("property_country", models.CharField(blank=True, max_length=200)),
                (
                    "type_price_paid_transaction",
                    models.CharField(blank=True, max_length=20),
                ),
                ("record_status", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
            },
        ),
    ]
