# Generated by Django 4.1.7 on 2023-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_uk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="duration",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="price",
            name="postcode",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="price",
            name="price",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="price",
            name="property_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="price",
            name="record_status",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="price",
            name="type_price_paid_transaction",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
